name: Package

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
    CF_API_KEY: ${{ secrets.CF_API_KEY }}
    WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
    WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
    GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v1
        with:
          fetch-depth: 100

      - name: Package
        uses: BigWigsMods/packager@master
        
          
      - name: Package Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g classic -m .pkgmeta-classic
          
      - name: Package BCC
        uses: BigWigsMods/packager@master
        with:
          args: -g bc -m .pkgmeta-bc
